version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-olltv
    restart: always
    ports:
      - "27017:27017"

  rabbitmq:
    container_name: rabbitmq-amedia
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 12345

  postgres:
    image: postgres:10.5
    container_name: postgress-amedia
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'